apiVersion: v1
kind: Service
metadata:
  labels:
    name: mnist-tf
  name: mnist-tf
  namespace: dotscience-deploy-demo
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: mnist-tf
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.228.2.4
