apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: dotscience-deploy-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: deploy-demo.dotscience.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mnist-app
          servicePort: 8080

--- 

apiVersion: v1
kind: Service
metadata:
  labels:
    name: mnist-app
  name: mnist-app
  namespace: dotscience-deploy-demo
spec:
  type: ClusterIP
  ports:
  - name: app
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mnist-app
  sessionAffinity: None

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: force
  labels:
    app: mnist-app
  name: mnist-app
  namespace: dotscience-deploy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mnist-app
    spec:
      containers:
      - env:
        image: quay.io/dotmesh/dotscience-deploy-demo:latest
        imagePullPolicy: Always
        name: mnist-app-container
        env:
        - name: PORT
          value: '8080'
        ports:
        - containerPort: 8080
          protocol: TCP
        
