apiVersion: v1
kind: Service
metadata:
  labels:
    name: mnist-app
  name: mnist-app
  namespace: dotscience-deploy-demo
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mnist-app
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 35.228.2.183
